# Basic configuration for lust.

[colors]
# Main Colors
unrecognized_file = "gold"
recognized_file = "yellow"
executable_file = "lime"
dir = "dodgerblue"

# Link
dead_link = "red"
link = "cyan"

# special files
socket = "green"
blockdev = "green"
chardev = "green"

# Access Modes
write = "darkkhaki"
read = "limegreen"
exec = "red"
no_access = "indianred"

# Age
day_old = "mediumspringgreen"
hour_old = "lime"
no_modifier = "seagreen"

# File Size
file_large = "orange"
file_medium = "gold"
file_small = "peachpuff"

# Random
report = "white"
user = "moccasin"
tree = "cyan"
empty = "yellow"
error = "red"
normal = "darkkhaki"
inode = "moccasin"

# Git
addition = "chartreuse"
modification = "darkkhaki"
deletion = "darkred"
untracked = "darkorange"
unchanged = "forestgreen"

[icons]
ai = ""
android = ""
apple = ""
audio = ""
avro = ""
c = ""
clj = ""
coffee = ""
conf = ""
cpp = ""
css = ""
d = ""
dart = ""
db = ""
diff = ""
doc = ""
docker = ""
ebook = ""
env = ""
epub = ""
erl = ""
file = ""
font = ""
gform = ""
git = ""
go = ""
gruntfile.js = ""
hs = ""
html = ""
image = ""
iml = ""
java = ""
js = ""
json = ""
jsx = ""
less = ""
log = ""
lua = ""
md = ""
mustache = ""
npmignore = ""
pdf = ""
php = ""
pl = ""
ppt = ""
psd = ""
py = ""
r = ""
rb = ""
rdb = ""
react = "ﰆ"
rss = ""
rubydoc = ""
sass = ""
scala = ""
shell = ""
sqlite3 = ""
styl = ""
tex = ""
ts = ""
twig = ""
txt = ""
video = ""
vim = ""
vue = "﵂"
windows = ""
xls = ""
xml = ""
yarn.lock = ""
yml = ""
zip = ""
